### ISSUE TITLE
艦娘一覧で「Lv99より小さい」が「Lv53より小さい」に変わる

### ISSUE THREAD

**Issue by headsupsevens** [Sdk0815/logbook-kai#13]
### 問題概要
艦娘一覧で「Lv99より小さい」という条件が「Lv53より小さい」に変わってしまいます。

### 再現方法
1. '所有艦娘一覧' を開く
2. フィルターで「Lv99より小さい」という条件を設定する
3. '所有艦娘一覧' を閉じる
4. '所有艦娘一覧' を開く
5. フィルターの条件が「Lv53より小さい」に変わっている

### 本来予想される動作
艦娘一覧を一旦閉じて開き直しても、フィルターの条件は「Lv99より小さい」のままになる。

**Comment by Sdk0815** [comment]
@headsupsevens 本当ですね…。こちらでも確認できました。原因を調べて対応します。ご報告ありがとうございます。

**Comment by Sdk0815** [comment]
原因がわかって修正ができました。次のバージョンで修正されます。よろしくお願いします。

**Comment by Sdk0815** [comment]
`v20.11.1` で修正されました。よろしくお願いします。

**Comment by headsupsevens** [comment]
ありがとうございました。
