### ISSUE TITLE
半日分の戦果が見たい

### ISSUE THREAD

**Issue by headsupsevens** [Sdk0815/logbook-kai#14]
### 機能拡張で解決したい課題
直近の午前（2:00～14:00）または午後（14:00～2:00）、半日分の戦果が見たいです。
戦闘ログの高度な集計で、提督経験値を集計するスクリプトを組んでみたのですが、自動更新されないのと、戦闘ログを閉じると高度な集計も閉じてしまい、不便でした。

### 実装してほしい機能について
直近の半日分の戦果が自動更新で表示される専用のダイアログが欲しいです。

**Comment by Sdk0815** [comment]
@headsupsevens ご要望ありがとうございます。検討してみますね。

**Comment by Sdk0815** [comment]
@headsupsevens 時間が取れたので実装してみております。専用のダイアログも考えたのですが、表示する情報量が多くないので以下のように母港タブに埋める実装にしてみました。

![image](https://user-images.githubusercontent.com/3181895/100116423-115afa80-2eb7-11eb-936b-e83f1961c2f1.png)

右に今の時間帯(2時～14時か14時～26時)の戦果、左にはその前の時間帯の戦果を表示しています。なので基本的に左は出撃等しても変わらず（既に確定した時間帯なので）、右は出撃して帰投するたびに増えていきます。更新されるタイミングは基本的には母港に帰投したタイミングになりますね。（左が9時からになっているのは私が今日ログインしたのが9時台だったからです。）

戦果の計算方法は、2時以降または14時以降に最初に取得した提督経験値をそれぞれの時間帯の基準提督経験値とし、

```
戦果 = ((その時点での提督経験値) - (基準提督経験値)) * 7 / 10000　（小数点以下3桁まで）
```

で計算しています。つまり提督経験値が増えるものはすべて計算に含まれるので、出撃だけでなく演習や遠征等も戦果に含まれることになります。また、基準提督経験値も「2時以降または14時以降に最初に取得した提督経験値」が基準なので、その時間をまたいだ出撃の分など微妙なものが含まれないこともあり、完全に正確な戦果を表示しているとは限らないです。また EO や任務による戦果も提督経験値には含まれないため、この戦果計算にも含まれません。以上の仕様となりますがご了承いただけると嬉しいです。

**Comment by headsupsevens** [comment]
ありがとうございます。
個人的には、とても良いと思いました。
人によっては、メインウィンドウの表示が変わるのが嫌な人もいると思いますので、設定で戦果表示を消せるようにした方が良いかもしれないなと思いました。

**Comment by Sdk0815** [comment]
@headsupsevens はい、おっしゃる通りで戦果は気にしない提督のみなさんも多いと思うので、このように設定で変更できるようにしてあります。

![image](https://user-images.githubusercontent.com/3181895/100164681-b8618580-2efb-11eb-8ed5-50cd958fa5c0.png)

戦果以外も不要な方もいるかもしれないのでついでに消せるようにしてありますが、戦果以外は多くの人が使うと思うので初期状態は上記のようにしました。

**Comment by headsupsevens** [comment]
ありがとうございます。
良いですね。

**Comment by Sdk0815** [comment]
変更をマージしました。次のバージョンで利用可能になります。

**Comment by Sdk0815** [comment]
`v21.1.1` に取り込まれましたのでご確認ください。よろしくお願いします。

**Comment by headsupsevens** [comment]
確認しました。
ありがとうございました。
