### ISSUE TITLE
遠征条件確認の誤判定

### ISSUE THREAD

**Issue by megarala** [Sdk0815/logbook-kai#16]
### 問題概要
遠征条件確認で（大）成功と出ていたのに失敗になってしまいました。
しっかり補充もしてあったため、原因が全く掴めません。

### 再現方法
E1の遠征について、火力462、対空432、対潜331、索敵321となっているのに失敗になってしまいました。
以下、帰ってきた編成をそのまま晒します。
![攻略編成_20201111-034724232](https://user-images.githubusercontent.com/69301684/98717610-a26aa580-23d0-11eb-9f9d-8188167042df.png)

**Comment by Sdk0815** [comment]
@megarala ご報告ありがとうございます。（logbook-kai内の計算ではなく）キャプチャにある対潜値を合計したところ331なので計算ミスではなさそうです。となると艦これ側で対潜値を計算するのにここに表示されているのと違う計算方法をしていることになりますが、もしかすると[このあたり](https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81#about_stat)に記述のあるこれかもしれません:

- 艦載機を載せたスロット機数が2以上の場合
    - 実際の対潜値 = ⌊艦載機の素の対潜値×(0.65 + √(スロット機数-2)×0.1)⌋

旗艦の足柄さんが装備している「零式水上偵察機11型乙(熟練)」の対潜値は8で、搭載数は2なので

実際の対潜値 = (8x(0.65+√0x0.1))=5.2

となり、整数にするため5としてカウントされます。となると実際は331ではなく328なので失敗したということかもしれません。

実はこのあたりの計算式は艦これ内部の計算式でユーザーの検証によって導き出されたものであるため絶対に正しいとは言えないという背景があります。同じ理由で遠征条件の判定に装備の改修値の補正はあえて組み込んでおりませんが、こちらは値が加算されるので安全側の間違いしか起こさない（「失敗」と出ていて成功することはあっても「成功」と出ていて失敗することがない）ため問題はないと考えております。ですが艦載機のほうは値が減るケースがあるためこの考え方が当てはまらず、実際にこの issue が起きているということになります。

このような事情から考えると、艦載機による対潜値の扱いは0.65掛けにするのが安全サイドであると言えそうなので、その方向で変更を検討しようと思います。

**Comment by Sdk0815** [comment]
`v20.11.1` で修正されました。よろしくお願いします。
