### ISSUE TITLE
任務の進捗を定期的に保存してほしい

### ISSUE THREAD

**Issue by kumanekosan** [Sdk0815/logbook-kai#18]
### 機能拡張で解決したい課題
航海日誌を手動で終了させずPCをシャットダウンしてしまった際に、進捗が保存されず、
どこまで任務が完了しているのか分からなくなってしまうことが有り不便です。

### 実装してほしい機能について
任務の進捗の保存タイミングが恐らく航海日誌の終了タイミングのみとなっていると思われるため、
任務に更新があった場合、もしくは一定時間間隔で保存を行っていただければと思います。

**Comment by Sdk0815** [comment]
@kumanekosan ご要望ありがとうございます。現状は任務の進捗だけでなくすべてのデータ（遠征や入渠の状況、艦隊の状況など）が基本的には同じタイミングで保存され、そのタイミングは以下になります：
- logbook-kai を終了したとき
- 設定を変更したとき
- 艦これを起動した直後

ですので、艦これを終了せずずっとプレイし続けて設定を変えてない状態で正常終了させなかった場合は保存されません。

そのあたりを実装したのが私ではないので正確な意図はわからないのですが、すべてのデータを同時に上記のタイミングにのみ行っているのはデータ間の不整合を防ぐためではないかと思います。例えばある艦隊に属している艦を入渠させたというデータの処理を行っているとき、入渠している艦の一覧を更新し、さらに艦隊のタブでも入渠状態にする必要がありますが、前者の処理を行ったタイミングでデータの保存が行われてしまうと、再起動したときに入渠したことになっている艦が艦隊タブでは入渠してないことになる、という感じです。（例はわかりやすくするため目に見える例を書いておりますが、実際には内部データの不整合、さらにエラーが発生する可能性もあります。）起動時であればこのような状況には陥りにくく、艦これが終了済みと考えられる停止時には絶対に起きないのでこのような実装になっているのだと思われます。

このような理由から定期的に保存するのはいつ保存されるかがわからないので得策ではないです。任務の受諾時・停止時も実はあまりよくなくて、このタイミングでは艦これとの通信を短時間の間に2回行っているので上記のような不整合が起きやすいタイミングです。ほかにいい方法がないか検討してみますね。

**Comment by Sdk0815** [comment]
色々検討した結果、戦闘終了時に呼ばれるAPIのデータを処理したタイミングであれば前後に他のデータを処理することがなく不整合が起きにくいと考えられるので、そのタイミングでデータを保存することにしました。次のバージョンで変更が取り込まれる予定です。

**Comment by Sdk0815** [comment]
`v20.11.1` で対応が取り込まれした。よろしくお願いします。
