### ISSUE TITLE
chrome、chromiumでのプロキシ設定について

### ISSUE THREAD

**Issue by menmy24** [Sdk0815/logbook-kai#21]
### 問題概要
Google chrome ＆ chromium でプロキシ設定ができない？

先日、PCを新調し航海日誌の設定を進めていましが [ブラウザの設定](https://github.com/Sdk0815/logbook-kai/blob/master/how-to-preference.md)を元に設定していたが艦これの読み込み画面そのものにたどりつけなかったり色々とYoutubeに他の方が上げている方法など(Firefox版も)試して見ましたが個人では解決できませんでした。

プロキシ設定方法の更新と私の環境でプレイできるように解決方法を教えてください。

### 動作環境
ブラウザ Google chrome ＆ chromium
 - OS:windows10 home
 - Java: 8
 - Version: 271

プロキシ拡張機能
[Proxy SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif/related?hl=ja)

**Comment by Sdk0815** [comment]
@menmy24 報告ありがとうございます。すみません、通知メールを見逃したのか気づくのが遅れました。

設定のページは確かに情報が古くなっていて今そのまま適用できるかわからないところはありますが、数ヶ月前に私が自分の環境で設定した時には特に問題なかったので、 logbook-kai としては大筋の動作（スクリプトの生成等）は問題なく動作していると思います。ですので、 @menmy24 さんが行ったステップを詳細に、文章で難しい部分はスクリーンショット等でコメントに追記していただけますでしょうか？また生成された pac ファイルや logs 以下のエラーファイルなども添付していただけると何かわかるかもしれません。

よろしくお願いします。

**Comment by menmy24** [comment]
新しくlogbook-kai_20.11.1をDLし解凍、launch.batから起動して12月分へ更新。
再度、起動させプロキシ設定を元にpacファイルを生成
SwitchySharpにpacファイルを読み込み保存。

艦これを起動するとDMM等の枠？は出てきても艦これ本体が表示されません。
Logsフォルダ内には app.log が生成されてますが中には何も書かれていませんでした

[proxy.zip](https://github.com/Sdk0815/logbook-kai/files/5682901/proxy.zip)

![image](https://user-images.githubusercontent.com/75358314/101981565-37eba480-3cb1-11eb-807c-e220b4c7ecc4.png)

**Comment by Sdk0815** [comment]
@menmy24 ありがとうございます。設定自体は問題なさそうに見えますね。となるとほかのブラウザでも動作してないことを考えると、 logbook-kai を通して通信することが拒否されている可能性が考えられます。ファイアウォール等通信に影響するソフトウェアが動作しているのであれば、一度それらを切って試していただけますでしょうか？もしそれで通信が可能になれば Java を通しての通信が許可されていない可能性があるかもしれません。

それでも変化がないようであれば、ログが出ていないとなかなか解析が難しいのですが、コマンドプロンプトから起動してみるのは可能でしょうか。例えばこんな感じになります（Java へのパス等はご自身の環境に合わせてください）：
```
C:\Programs\logbook-kai_java8>C:\Programs64\jdk8u252-full\bin\java -jar logbook-kai.jar
2020-12-12 19:57:59,108 INFO  o.e.j.s.Server [Thread-4] jetty-9.0.z-SNAPSHOT
2020-12-12 19:57:59,169 INFO  o.e.j.s.h.ContextHandler [Thread-4] Started o.e.j.s.ServletContextHandler@daf13a0{/,null,AVAILABLE}
2020-12-12 19:57:59,181 INFO  o.e.j.s.ServerConnector [Thread-4] Started ServerConnector@5319c838{HTTP/1.1}{localhost:8888}
```
この状態で接続を行ってみると何かエラー等が表示されるかもしれません。

**Comment by menmy24** [comment]
ブラウザとlogbook以外のソフトは落とし、ファイアウォールも一時的に無効化したりしましたが上で送ったように変わらなかったです。

コマンドプロンプトもここから全く動きませんでした......
```
2020-12-12 21:20:23,076 INFO  o.e.j.s.Server [Thread-4] jetty-9.0.z-SNAPSHOT
2020-12-12 21:20:23,203 INFO  o.e.j.s.h.ContextHandler [Thread-4] Startedo.e.j.s.ServletContextHandler@47afe08a{/,null,AVAILABLE}
2020-12-12 21:20:23,217 INFO  o.e.j.s.ServerConnector [Thread-4] Started ServerConnector@32de6f6c{HTTP/1.1}{localhost:8888}
```

**Comment by Sdk0815** [comment]
@menmy24 なるほど…　悩ましいですね。ログレベルを debug にした jar を作ってみました。公式の `logbook-kai.jar` をどこかにバックアップして、こちらの zip を展開して出てくる jar に置き換えて、上と同様にコマンドプロンプトから実行していただけますか？かなりの量のメッセージが画面に出ることになると思いますので、下の例のように出力をリダイレクトしてそのファイルを添付していただくほうがいいかもしれません。

```
C:\Programs\logbook-kai_java8>C:\Programs64\jdk8u252-full\bin\java -jar logbook-kai.jar > log.txt
```

やり方としては：
1. ファイルを置き換える
2. コマンドプロンプトから起動する
3. 艦これの起動を試す（状況は変わらないと思うので恐らく画面は表示されない）
4. logbook-kai を停止する
5. ファイルを（zip で圧縮して）添付する

[logbook-kai.zip](https://github.com/Sdk0815/logbook-kai/files/5683325/logbook-kai.zip)

**Comment by menmy24** [comment]
わざわざありがとうございます。
コマンドプロンプトからの実行方法だけできなかったのでバッチファイルから起動させそのログもzipに入れておきました。
艦これは母港まで行けました。

[logbook-kai-java11_20.11.1.zip](https://github.com/Sdk0815/logbook-kai/files/5683965/logbook-kai-java11_20.11.1.zip)

**Comment by Sdk0815** [comment]
@menmy24 ありがとうございます。あれ、母港まで行けたとおっしゃってるのはどういうことでしょうか？ jar を置き換えたら状況が変わったということでしょうか？その状態でもまだ logbook-kai には各種データが表示されてないということでしょうか？

**Comment by menmy24** [comment]
言葉足らずですみません。
jarファイル置き換えて艦これを起動しlogbook経由でプレイは出来てるようなのですが一部艦娘の画像と装備アイコンが編成を変えたりしても表示されません。
演習も回してみましたが特に切断されるようなことはありませんでした。

![image](https://user-images.githubusercontent.com/75358314/102000517-a0776780-3d2b-11eb-87b3-49f00af228ee.png)

**Comment by Sdk0815** [comment]
@menmy24 なるほど、状況が改善したようでよかったです。お送りした JAR は `v20.12.1` と比べてログレベル以外の変更がないので、その JAR ならうまくいくと言うのはあまり考えられないんですね。そこで一つ気になったのは、添付していただいた zip ファイルの名前が `logbook-kai-java11.zip` になっていて、これは Java 11 用のパッケージの名前なのです。お送りした JAR ファイルは（この issue の先頭に Java 8 と書かれていたので）Java 8 用のものをお送りして、それでうまくいったということは、もしかしてダウンロードされたパッケージが違うのではないでしょうか？Java 8 であれば、ダウンロードするパッケージは(`logbook-kai-java11_20.12.1.zip`ではなく) `logbook-kai_20.12.1.zip` のほうになります。

装備や艦娘の画像は Release の最後にあるように、ブラウザのキャッシュを一度クリアしていただければ（徐々に）表示されるようになると思いますのでお試しください。

**Comment by menmy24** [comment]
Java 8 用である logbook-kai_20.12.1.zip から起動したところjarすり替えせずに艦娘画像等も問題なく起動できました。
java11の方がDLリストの上にあったのでそちらをダウンロードしてたみたいです
かなり初歩的なミスなのに対応していただきありがとうございました。

**Comment by Sdk0815** [comment]
@menmy24 いえいえ、解決したようで良かったです。今後ともよろしくお願いします！
