### ISSUE TITLE
TP(輸送量)が表示されるようにしてほしい

### ISSUE THREAD

**Issue by sephisephi** [Sdk0815/logbook-kai#22]
### 機能拡張で解決したい課題
駆逐艦数、大発数等によって変化する現在の輸送量を表示してほしい（S時、A時）
可能であれば、連合艦隊時には合計輸送量を表示してほしい。

### 実装してほしい機能について
制空値等の部分に追加してほしいが、必要な場面が限られるので設定の表示を切り替えられるようにすると良いと思います。

**Comment by Sdk0815** [comment]
ご要望ありがとうございます。確かにイベント中の限られたときにしか使わないのでどう表示したらよいかは考えないといけないですね。検討してみます。

**Comment by Sdk0815** [comment]
いろいろ検討しましたが、現状でもそこそこ多くの項目が常時表示されているので、普通に項目を追加する方法を選びました。連合艦隊時には第一第二バラバラに表示されることになりますが、うまく表示する方法が現時点で思いつかなかったので特に変更は行なっておりません。従って以下のように表示されます。

![image](https://user-images.githubusercontent.com/3181895/102849978-a96ae600-445b-11eb-982b-1ad797e83f02.png)

次のバージョンで利用可能になりますのでリリースまでいましばらくお待ちください。

**Comment by Sdk0815** [comment]
`v21.1.1` に取り込まれましたのでご確認ください。よろしくお願いします。
