### ISSUE TITLE
現在の燃料、弾薬がパーセント表示されるようにしてほしい

### ISSUE THREAD

**Issue by sephisephi** [Sdk0815/logbook-kai#23]
### 機能拡張で解決したい課題
各マスでの戦闘後、現在の艦隊の燃料、弾薬をバー表示だけでなくパーセント表示してほしい。
※別途計算せずにペナ回避のための洋上補給の個数や要否を判断したい

### 実装してほしい機能について
各艦の燃料弾薬バー部分にポインタを移動した際に現在の燃料、弾薬がパーセントで見えるようにすれば現行デザインを崩さずに実装可能と思います。

**Comment by Sdk0815** [comment]
ご要望ありがとうございます。おっしゃる通りのデザインで可能だと思いますが、実装方法を検討してみます。

**Comment by Sdk0815** [comment]
変更をマージしました。次のバージョンがリリースされるまで今しばらくお待ちください。よろしくお願いします。

**Comment by Sdk0815** [comment]
`v21.1.1` に取り込まれましたのでご確認ください。よろしくお願いします。
