### ISSUE TITLE
メモリ不足が発生します。

### ISSUE THREAD

**Issue by lesserteramon** [Sdk0815/logbook-kai#26]
### 問題概要
航海日誌自体の問題なのかどうかも明確ではないのですが、艦これをやっていると、不意にJavaSEがメモリ不足を警告するダイアログをポップアップするようになりました。
最初は何のダイアログかわからず、しばらく(20秒程)放置していたところ、航海日誌が強制終了されてしまい、それに伴ってブラウザの艦これの画面がエラーになりました。

改になる前の航海日誌から利用させて貰ってましたが、このようなことはありませんでした。
最初に起きたのは昨日1/2で、たまたま何かPCの調子がおかしかったのかと考えていましたが、本日1/3に再度発生しましたので報告させていただきました。
ポップアップするダイアログに対象がJava SEであると表示されていること、Javaを使っているプログラムが航海日誌だけであること、ダイアログにある「プログラムを終了する」ボタンを押すと航海日誌だけが終了されることから、航海日誌の問題ではないかと考え、つい先日行われた航海日誌のアップデートで何かあったのではと思いました。

確保したメモリを開放しないままになっているようなところが無いか、他に同様の報告が無いかをご確認いただけませんでしょうか。

### 再現方法
確実に再現できる方法は明確にはわかりません。本日発生した際にやっていたことで言うと以下の通りです。
・航海日誌を起動
・Chromeで艦これを実行
・同じChromeのウインドウで別タブを開き、艦これWikiとぜかましねっとを開いていた
・Chromeの別ウインドウを開き、艦これの疲労抜きの時間待ちの間、Youtubeの動画を見ていた
　(艦これ画面は操作していない状態)
これだけです。

昨日1/2に発生したときは、現在のイベントのE4-3のラスダンに突入し、ボス戦開始のタイミングでSSを撮るため、「画面キャプチャ」を「連続」で「直接保存」を開始して数秒後に起きました。このままラスダンの戦闘が終わるまで持たないかな～？と思って放置していたところで前述の通り航海日誌が落ちて艦これ画面がエラーになりました。

### 本来予想される動作
メモリ不足が発生しない。

### スクリーンショット
もしかしたらそのうち再発生するかも知れませんが、現時点では再現できてません。

### 動作環境
 - OS:　Windows7 Ultimate 64bit　（既にEOLですが...）
 - Java: 　1.8.0.271
 - Version:　航海日誌 20.12.1

### その他
航海日誌側の問題ではなく、私のPC側の問題である可能性もありますので、何か確認すべき点がありましたらご指摘いただけるとありがたいです。

**Comment by Sdk0815** [comment]
@lesserteramon ご報告ありがとうございます。前回の更新に含まれた変更で悪さをしているものがないかは一応確認してみますが、現時点で私を含め他に報告がないため変更が原因である可能性は低いように思います。何かわかりましたらまた追記します。

**Comment by Sdk0815** [comment]
@lesserteramon その後も変更内容を確認してみましたが、特に問題になりそうなものは見つかりませんでした。 @lesserteramon さん以外にこのような問題に直面してるという報告も特になさそうです。であればもしかするとそちらの環境のJavaに対してもっとメモリを割り当てると起きなくなる、起きにくくなる可能性があるかなと考えられます。例えば launch.bat を使って起動されているのであれば、このファイルを編集して

> SET JVM_OPT=-XX:MaxMetaspaceSize=256M

この行を

> SET JVM_OPT=-XX:MaxMetaspaceSize=768M -Xmx768m

のように -Xmx をつけて起動してみるという感じです。（これは私が自分の環境で使っているものですが、どの値がいいのかはそれぞれの環境によると思いますので、いろいろ試してみる必要があるかもしれません。）

このような感じなのでこちらは一旦 close させていただきますが、もし他の方の環境でも顕著にメモリ不足が起きるようになったなどの報告がありましたらまた reopen したいと思います。よろしくお願いします。

**Comment by lesserteramon** [comment]
ご回答ありがとうございます。
お手数をお掛けしたようで申し訳ありません。

報告して以来、なぜか全く発生しなくなったため、本当にたまたま私のPC環境がおかしくなっていただけという疑いが強いかと思います。

お騒がせして申し訳ありませんでした。
今後ともよろしくお願い致します。
