### ISSUE TITLE
編成記録に基地航空隊の編成も追加していただきたい

### ISSUE THREAD

**Issue by Airema** [Sdk0815/logbook-kai#27]
### 機能拡張で解決したい課題
自身の編成を共有するにあたって、基地航空隊の編成を編成記録のメモ欄に手書きしている
機体名が長かったり、誤字などがあり、艦隊同様に編成を記録してくれるとありがたいです

### 実装してほしい機能について
編成記録にて、基地航空隊も編成テンプレートから選択できる機能の追加を希望します。
イベント時以外にも6-4/6-5で使用できればと考えています。

**Comment by Sdk0815** [comment]
@Airema ご要望ありがとうございます。検討します。

**Comment by Sdk0815** [comment]
申し訳ありませんが開発を停止させていただくことにしましたので未実装ですがクローズさせていただきます。ありがとうございました。
