### ISSUE TITLE
進捗不具合

### ISSUE THREAD

**Issue by mujo4920** [Sdk0815/logbook-kai#3]
### 問題概要
泊地周辺海域の安全確保を徹底せよ！の進捗の「7－2（セルG）」がカウントされない
またあ号の進捗もおかしい。あ号の条件内容からおそらく「任意の海域に３６回出撃」のカウントがあってない

### 再現方法
7－2ーGマスを３回S勝利しても艦これ自体の任務は５０％になっているが航海
日誌の進捗の「7－2（セルG）でボスS勝利３回（現在の値:０）」と全くカウントされない。
あ号に関してはカウント数を数えてないのでどう間違ってるかはわかりません

### スクリーンショット
任務一覧
![キャプチャ2](https://user-images.githubusercontent.com/68387034/93332825-664a1700-f85d-11ea-8ac6-91391c0a6a23.PNG)

泊地周辺海域の安全確保を徹底せよ！の進捗
![キャプチャ](https://user-images.githubusercontent.com/68387034/93332749-46b2ee80-f85d-11ea-9d0e-35d054bfe455.PNG)
このように５０％なのですが進捗は７－２－Gがカウントされません

あ号作戦の進捗
![キャプチャ3](https://user-images.githubusercontent.com/68387034/93333384-33ece980-f85e-11ea-9d0b-62e7e4af09c9.PNG)

### 動作環境
 - OS:Windows10
 - Java: ビルド1.8.0_261-b12
 - Version:20.9.2

以上よろしくお願いします

**Comment by Sdk0815** [comment]
@mujo4920 ご報告ありがとうございます。私のほうでは再現しておりませんので、何か条件があると考えられます。

![image](https://user-images.githubusercontent.com/3181895/93343362-5e916f00-f86b-11ea-9779-2df75e7378f5.png)

解析を行いたいので、お手数ですが以下の手順でファイルを取得して添付していただけますでしょうか？

1. logbook-kai を終了する
1. config/logbook.bean.AppQuestDuration.json と 海戦・ドロップ報告書.csv をどこかにコピーする（海戦・ドロップ報告書.csv が大きい場合は7-2-Gへの出撃が含まれてる行近辺だけでも大丈夫です）
1. zip 等で圧縮する
1. この issue にコメントと一緒に添付する（drag & drop でできます）

あ号のほうは私のほうでは既に完了していて確認できませんが、なぜカウントがあってないと判断されたのかもう少し詳しく記述していただけると助かります。例えばば出撃ログに今週の出撃回数等も出ていますので、そちらと実際にあ号が完了したときの回数を比べるなどしていただければと思います。

また、念のため確認ですが、艦これをプレイしているマシンは１つだけで常に logbook-kai を使っているということでよろしいでしょうか。複数のマシンを使っていたり logbook-kai を通さずに艦これをプレイしている場合は任務進捗のカウントは正しく行うことができないので一応確認させてください。

よろしくお願いします。

**Comment by mujo4920** [comment]
@Sdk0815 
ご指摘されて出撃ログを確認したところ7-1-Gの記載があらずAndroidでやっていたのを思い出しましたのでこちらはおそらく不具合ではなくこちらの確認不足でした。お手数おかけしました。

あ号の方もおそらくAndroid分のカウントがされてないかも知れません。以前ゲームの進捗状態と航海日誌の進捗がズレておりやっぱりバグなのかな？と思ったのですが先程の7-1-Gのことも考えるとAndroidの可能性がありこちらも思い違いかも知れませんのでスレッドをクローズいたします

**Comment by Sdk0815** [comment]
@mujo4920 そうでしたか、確認ありがとうございました。実は以前にも同様なことがありましたので、FAQあたりにちょっと記述しておいたほうがいいのかもしれませんね。

今後も何かありましたら遠慮なくお知らせください。よろしくお願いします。
