### ISSUE TITLE
遠征条件確認での艦隊対潜合計で、艦娘ごとの装備ボーナスが計算されない

### ISSUE THREAD

**Issue by rua-j** [Sdk0815/logbook-kai#30]
### 問題概要
遠征条件確認での艦隊対潜合計で、艦娘ごとの装備ボーナスが計算されていません。
メインウィンドウでの艦隊タブごとの「対潜合計」では反映されています。

### 再現方法
三式水中探信儀を装備した状態で、磯風乙改の対潜+2や時雨改二の対潜+3が反映されていないのを確認しました。

### 本来予想される動作
遠征条件確認での「艦隊対潜合計」に装備ボーナスを反映させて欲しいです。

### 動作環境
 - OS: Windows 10 Pro 20H2
 - Java: Oracle Java 1.8.0_281
 - Version: 21.1.1

**Comment by Sdk0815** [comment]
@rua-j ご要望いただきありがとうございます。遠征条件の対潜値の計算は通常の（表示されている）対潜値の計算と異なり、さまざまな要因を考慮にいれないといけない事情があります（例えば[このあたり](https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81#about_stat)）。以前は表示されている対潜値を使う計算方法を採用していたのですが、その方法だと合計の対潜値を大きく見積もってしまう問題がありました（#16）。対潜値を間違えて大きく見積もってしまうと、#16 で実際に起きていた通り false positive（成功と出ているのに失敗する＝遠征したことが無駄になってしまう）の問題が起きてしまうため、今は逆に間違えたとしても小さく見積もることで false negative（失敗と出ているのに成功することがある＝余分にステータス値を要求してしまうが、成功と出ている時には常に成功する）のほうに寄せています。その計算方法だと装備ボーナスを考慮することは（装備ボーナスが独立したデータとして送られてきているわけではないため）技術的に難しいのです。

艦これの艦娘のステータス画面に出ている対潜値を単純に合計するだけでよいなら簡単なのですが、実際はそうではないため現在のような実装になっております。以上の理由から装備ボーナスの反映は難しいため close させていただきますがご理解いただけると幸いです。今後ともよろしくお願いいたします。
