### ISSUE TITLE
起動時間に伴うCPU使用率の占用

### ISSUE THREAD

**Issue by sakura445** [Sdk0815/logbook-kai#36]
### 問題概要
タイトル通り、時間経過に伴いCPU使用率が100％まで張り付きます。
この問題は以前のバージョン(21.1.1の前、更に言えばfolk以前、バージョンが一桁の頃から)発生しておりました。
21.1.1の前までは「設定>一般」の通知全般をオフにすることで回避できてましたが、21.1.1以降はそれらの設定をオフにしても発生するようになっております。

### 再現方法
時間経過、もしくは長時間のスリープから復帰した際に必ず発生しますが、具体的なトリガーの特定には至っていません。
10時間程度起動していても占有が始まらないこともあれば、1時間程度で発生することもあります。
また、艦これ自体や航海日誌の操作を行わなくとも発生するので、特定の操作による発生ではないかと思われます。

### 動作環境
 - OS:Windows 10 Pro (Build:18363.1316)
 - java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-BellSoft-b10)
OpenJDK 64-Bit Server VM (build 25.232-b10, mixed mode)
 - Version:航海日誌 21.3.1

### その他
ダンプファイルを作成しております。
ファイル容量の関係から一旦アップロードは見送りますが、必要な解析はお伝え頂けますと当方にて行わせて頂きます。

**Comment by Sdk0815** [comment]
@sakura445 報告ありがとうございます。私の環境を含め５つぐらいの環境でどれも再現していないので（私もほとんど停止せずスリープしたりもしていますが、これまで見たことがないです）、なかなか解析及び修正は難しそうです。もし可能でしたら Eclipse 等の開発環境から起動していただいて、CPUが100%になっている時にどのスレッドを一時停止したらCPU使用率が下がるか等の調査をしていただけるとわかるかもしれません。

よろしくお願いします。

**Comment by sakura445** [comment]
@Sdk0815 ありがとうございます。
何分javaに関しましてはド素人な上、人様の完成したプロジェクトをデバッグすることもなかった物ですから、何が何やらと要ったところでございます。

さて、javaに関してほぼ理解がないためeclipseのスレッド操作が分からなかったものですから、VisualVMからCPU使用率を確認いたしました。
どのスレッドが何に対応しているのか分からないので、添付した画像をご確認頂けますと幸いです。


![crashed](https://user-images.githubusercontent.com/80173125/111177656-ca238180-85ed-11eb-849f-c28d738fc1cb.png)

**Comment by sakura445** [comment]
お久しぶりです。
何か追加で行えることがないかと思い2週間ほど覗かせていただいておりましたが、やはり問題の特定は難しいようですね。

見たところjavafxのスレッドが適切に終了されてないかと思われます。
cpu占有時も廃熱量がさほど増えていないので、恐らく[このページ](https://blog.regrex.jp/2018/10/31/java%E3%82%A2%E3%83%97%E3%83%AA%E3%81%A7cpu%E4%BD%BF%E7%94%A8%E7%8E%87%E3%81%8C%E7%88%86%E4%B8%8A%E3%81%8C%E3%82%8A%E3%81%99%E3%82%8B%E5%8E%9F%E5%9B%A0/)事例の様に、どこかで無限ループとしてまま処理を投げている箇所があるのかと思われます。

先にお伝えしております通り、javaに関してはずぶの素人でありますので、この話がとんだ見当違いでしたらお忘れください。
また、同様の事例をレポートされている方もいらっしゃらない様ですので、私の使用環境が動作範囲外だったと認識することで、この問題の解決とさせていただきます。

こちらのアプリケーションは非常に便利な機能が満載で適宜更新もなされているので、今後とも是非とも利用させていただきたいと思います。CPU使用率に関しては30分に1回程度再起動すればいい話ですし。
引き続き応援しておりますので、開発の方頑張られてください。

**Comment by Sdk0815** [comment]
@sakura445 お世話になっております。ご期待に添えず申し訳ありませんが、（お金をいただいて業務として開発しているものではないため）こちらとしてもなかなか時間が取れないことがあることをご承知おきいただけると幸いです。

上の内容を拝見したところ @sakura445 さんもおそらくJava以外のコンピュータ言語の開発の経験がおありのようなのでご理解いただけるかと思いますが、こちらの事例のように開発元で再現しない現象をデバッグするのは非常に難しく労力がかかるものなので、可能であればやはり再現する環境でデバッガでどのスレッドがどのあたりを実行している時にCPU使用率が上がるかまで突き止めないとなかなか解決が難しいと思います。ご提示いただいたようなループがあるとはあまり考えにくい（javafxのスレッドがループしていたらそもそも描画がされず固まってしまいます）ので、その現象が起きている際にはUIスレッドではない何かがループしている可能性はあります。

上に貼っていただいたスレッドのCPU使用率ですが、 `MissionPane.update()` は母港タブの遠征のところの描画なので毎秒更新される（残り時間が毎秒変わるため）ものになりますので、実際使用率を取ったことはないですがそれほど不自然な感じには見えません。それを確認するためには、CPU使用率が上がっていない初期の状態で何度か使用率を取ってみて、その後使用率が上がった後にも何度か取ってみてもしこのメソッドの使用率が著しいく上がっているなどの情報があれば何かヒントになるかもしれません。

手探りの状況で申し訳ないですがお時間がありましたらこのような調査をしていただけると助かります。よろしくお願いします。

**Comment by K019D1070** [comment]
原因を突き止めるには至っておりませんが,おそらくこの問題に関連していることだと思いますので報告を上げさせていただきます。先に要点を申し上げますとJVMに割り当てるCPUスレッド数を減らした結果症状の軽減に成功しました。

私の環境でも"不定の頻度で15秒間ほどJVMに割り当てている全てのCPUスレッドのUsageが100%になる"という現象が発生しています。
そのうえ厄介なことに発生している間はプロキシサーバーとしての機能も死んでいるようで,艦これの方では通信エラーが発生してしまうという致命的な症状になっています。

私はこの航海日誌を愛用しており,イベント海域での編成の試行錯誤にも役立てていますので,これでは非常に困るのでなんとかしたく思いましたが,Javaの知識がなく直接コードを検分することはできません。
そこで,Javaの知識が必要ない範囲でタスクマネージャーなどを利用して症状の発生条件を分析しました。

いかんせんいつ起こるかわからず,起こる頻度もまちまちでありまして,タスクマネージャーとずっとにらめっこしているわけにもいきませんので正確性に欠ける部分もあると思いますが,傾向として以下のことがわかりました。

- 動画エンコードなどでCPUを酷使しているときには発生しない
- メイン機のデスクトップPC(8C16T)では発生するがサブ機のノートPC(4C8T)では発生しない

これらのことから,JVMに割り当てられているCPUのスレッド数が多いと発生するのではないかと見当を付け,起動用の.batスクリプトを変更して割り当てスレッドを減らしました。
これがうまくハマったようでこの半年間この現象が原因と思われる通信エラーに遭遇しておりません。ただし,割り当てられたスレッドのUsageが100%になる現象は引き続き発生しており,その間は艦これの画面遷移などに伴う通信に時間がかかります。

以下に現在の起動用スクリプトを示します。
```
SET JVM_OPT=-XX:MaxMetaspaceSize=512M

set JAVA=C:\Program Files\BellSoft\LibericaJRE-11-Full\bin

start "" /affinity 0xF "%JAVA%\javaw.exe" %JVM_OPT% -XX:+UseG1GC -jar -XX:MaxGCPauseMillis=100 logbook-kai.jar
```
`start`コマンドの`affinity`オプションで0xFを指定することで私のCPUの16スレッドのうち半分の8スレッドをJVMに割り当てています。
また,LibericaJREは普段使いのJREではないのでJREのパスは変更してあります。
MaxMetaspacesizeが既定より大きくなっていますがなぜなのかは覚えていません。

全く見当違いな対策でしたらすみません。何か役立つことを願っています。

**Comment by Sdk0815** [comment]
@K019D1070 情報ありがとうございます。複数の環境で起きているということは何かしら（logbook-kai 自体の問題かどうかはまだ確定できませんが）問題が存在していると思いますので、他の方で同じ問題に遭遇している方に見ていただけるようまずは reopen しておきます。なかなか時間が取れずに申し訳ないですが、後日調査の協力をお願いするかも知れません。その時はよろしくお願いいたします。

**Comment by Sdk0815** [comment]
問題が解決してない現状で申し訳ありませんが、開発を停止させていただくことにしましたのでクローズさせていただきます。ありがとうございました。
