### ISSUE TITLE
通知のサラウンドについて

### ISSUE THREAD

**Issue by doreddono-to** [Sdk0815/logbook-kai#38]
大破進軍、ギミックなどでサラウンドが鳴りますが項目別に鳴る、鳴らないように個別に設定できるようにしてほしいです。
個人的に録画してるのですが少し気になってるので。
よろしくおねがいします。

**Comment by Sdk0815** [comment]
@doreddono-to ご要望いただきありがとうございます。サウンドを鳴らす鳴らさないに関しては設定できますが、録画に音が入るのが気になるのでしたら全て鳴らないように設定するのではご要望を満たせないでしょうか？大破進撃のみ非常に危険なため設定と関係なく警告音が鳴るようになっていますが、それを鳴らないような設定がほしいということでしたらお知らせください。

**Comment by doreddono-to** [comment]
返信遅れてすみません。
確認なのですが通知でサラウンドが鳴るのは「海域の変化」「大破進撃等」「ギミック完了時」だったでしょうか？
すみませんものすごくおる覚えだったのので。

**Comment by Sdk0815** [comment]
@doreddono-to 抜けがあるかもしれませんが、今確認したところサウンドが鳴るのは以下の場合になります：
- 大破進撃時
- 遠征完了時
- 入渠完了時
- ギミック解除、海域変化時
- 遠征出発時に遠征成功条件を満たしていない時

このうち上に書いたように大破進撃のみ「通知でサウンドを鳴らす」の設定と無関係に常に鳴るようになっており、それ以外はこの設定をオフにしていれば鳴らないはずです。（もしなるケースがありましたらバグになります。）

**Comment by doreddono-to** [comment]
返信遅れて申しわけ有りませんでした。
大破進撃は無条件で鳴るのは知りませんでした^^;
自分が機能説明を見逃したみたいですね。
自分は大破進撃時以外は鳴らないのがいいので「通知でサラウンドを鳴らす」のチェックを外すだけでいいでしょうか。
解決しました。有難うございました。

**Comment by Sdk0815** [comment]
@doreddono-to 確認ありがとうございます。解決したとのことなのでこちらのissueはクローズさせていただきます。他にも何かありましたらまた遠慮なくお知らせください。よろしくお願いします。
