### ISSUE TITLE
疲労回復のトースト通知のオプション追加要望

### ISSUE THREAD

**Issue by kakkou** [Sdk0815/logbook-kai#39]
### 機能拡張で解決したい課題
疲労回復タイミングの見逃し。

### 実装してほしい機能について
艦隊の疲労回復予定時間になった際のトースト通知機能が欲しいです。
第一以外は遠征旗艦直後などの疲労減少もあると思われるので艦隊単位で通知をオンオフできるとなおありがたいです。

**Comment by Sdk0815** [comment]
@kakkou ご要望いただきありがとうございます。検討します。

**Comment by Sdk0815** [comment]
@kakkou 開発中の状況ですが恐らく以下のような仕様になりそうです。今は私の環境で動作確認中です。

- 設定に疲労回復予想時刻になったらトースト通知を表示するオプションを追加
- 出撃中を除いて、遠征中の艦隊を除く艦隊に cond 値が 49 未満の艦がいて疲労回復予測時刻を超えた場合トースト通知を表示

ご要望にありました艦隊ごとの設定について検討したのですが、上のような仕様（遠征中の艦隊を除く）にすると特に実装しなくても邪魔にならないので必要なさそうです。

またある時刻から3分経ったら cond 値が 3 回復するのは知られていますが、実は **「どの時刻から3分経ったら回復するのか」というのはデータとして送られてきておりません** 。ですので logbook-kai では艦娘の情報が送られてきた時（母港に戻った時）に cond 値が変化したら、その時刻を起点の時刻としています。そのため実際は本来の疲労回復時刻と比べて最大3分のずれが生じることになります。これは既に表示している「疲労回復」の時刻についてもそうですし、今回実装中のトースト通知についても同様の挙動となりますことはご承知おき下さい。

また、この挙動のために、母港にしょっちゅう戻っているような時にはトースト通知がされないことになります。例えば cond 値46の艦がいる場合に以下のような状況だった場合ですが：
- 0:00 cond値46
- 0:01 実際の疲労回復時刻
- 0:03 logbook-kai が表示している疲労回復時刻

この場合、0:03まで放置すればトースト通知が表示されますが、0:01から0:03までの間に帰投するとその瞬間に cond 値が49となってデータが更新されるため通知されないことになります。ですがこの機能の目的は疲労がある場合に疲労が抜けるまで放置してから出撃したいということだと思いますので、放置していない時に通知されないのは問題ないかと思っています。

**Comment by Sdk0815** [comment]
`v21.5.2` にてリリースされましたので close します。よろしくお願いします。
