### ISSUE TITLE
所有艦娘の一覧機能で札がついていない艦娘を表示させられるようにして欲しい

### ISSUE THREAD

**Issue by sephisephi** [Sdk0815/logbook-kai#40]
### 機能拡張で解決したい課題
所有艦娘の一覧機能で札がついていない艦娘を表示させられるようにして欲しい

### 実装してほしい機能について
所有艦娘で札がついている艦娘は勝手にタブが追加されて切り替えて確認できるが
札がついていない艦娘もタブを追加するか、フィルタで選択して確認できるようにして欲しい
※イベント時は残っている艦娘から編成を考えることが普通だと思いますので

### その他
もし他に何かあればなんでも。

**Comment by Sdk0815** [comment]
@sephisephi ご要望いただきありがとうございます。検討します。

**Comment by Sdk0815** [comment]
@sephisephi こちら実装中ですが、以下のような仕様になる予定です。

- 設定で「所有艦娘一覧にラベル単位のタブを追加」がオンになっている場合は、所持している艦娘の中に海域札がついている艦がいる場合は「海域札なし」タブを表示
  - ご存知の通りlogbook-kaiは海域札とは別に任意の「ラベル」を艦娘に付与する機能がありますが、この「海域札なし」タブの判定条件は海域札のみで手動で付けたラベルの有無とは関係ありません
  - 上記のような条件のため、そのタブに表示される艦娘も同様に海域札がついていない艦娘となります（つまり任意に付与したラベルがついていて海域札がついていない艦娘も含まれます）
  - 海域札がついている艦娘がいる時のみ表示するようにしているのは、イベント終了後は全員タブと同じ内容となってしまうためです
- ラベルフィルターに「(ラベルなし)」を実装
  - こちらは「海域札なし」とは異なり、任意のラベルも含め何もついていない艦娘のみを表示するフィルターとなります

ちょっと複雑かもしれませんが、ご要望の主目的はイベントでまだ海域札のついていない艦に絞りたいということだと思いますので、このような実装にしています。今動作確認中です。

**Comment by Sdk0815** [comment]
`v21.5.2` にてリリースされましたので close します。よろしくお願いします。
