### ISSUE TITLE
所有艦娘一覧のカラム位置が事実上設定できない

### ISSUE THREAD

**Issue by HrhtAtKanColleInKanoya** [Sdk0815/logbook-kai#43]
### 問題概要
所有艦娘一覧のカラム位置が事実上設定できない
### 再現方法
所有艦娘一覧のカラム位置を移動すると再起動でデフォルトに戻る。
１．「所有艦娘一覧」を開く
２．任意のタブのカラムを別の列へ移動
３．再起動
４．カラムを移動したタブを再度表示

### 本来予想される動作
ユーザーが設定したカラムの位置はユーザーが再設定するまでその状態のままであるべき。
ただし、Ver.UPなどでデフォルト状態に戻ることを事前にアナウンスした場合を除く

### スクリーンショット
![起動時](https://user-images.githubusercontent.com/84298721/118970720-819b9200-b9a9-11eb-9a8c-190735b615a1.jpg)
起動後最初の表示

![カラム変更](https://user-images.githubusercontent.com/84298721/118970736-87917300-b9a9-11eb-9850-d8c8987f21e3.jpg)
カラム変更後

![起動時](https://user-images.githubusercontent.com/84298721/118970753-8c562700-b9a9-11eb-8799-8cf05268cd30.jpg)
再起動後、最初の表示

### 動作環境
 - OS:windows10 Pro 20H2
 - Java: openjdk version "1.8.0_275"
 - Version:（logbook-kaiの？）
![バージョン情報](https://user-images.githubusercontent.com/84298721/118971484-739a4100-b9aa-11eb-99e6-6c64ef6b8f14.jpg)

### その他
艦娘一覧のフィルタ機能が必要十分な内容で設定/解除もしやすく、この機能がないと遠征メンバーのキラ付けやキラ付け遠征ができない程度にlogbook-kaiに依存したプレイをしている提督です。
この艦娘一覧にカラム移動の機能があると、艦隊の性能（Lv.・火力・対潜能力・etc.）制限あり遠征でのメンバーチョイスを楽にしてくれます。
この機能とメイン画面で艦隊性能を一覧できる機能を併用して性能調整を捗らせていただいてます
個人的にメイン画面の性能値と所有艦娘一覧に表示する性能値のカラムを同じ順序にできると（勝手に）思っていたのですが、その度に「雷装(素)」のカラム位置が元に戻るのに気づいてしまって、せっかくいい機能なのにもったいない、という気持ちを若干もってます。
一応ユーザー設定を勝手に変更する、という現象なのでバグ報告にしてはいますが、もし対応していただければうれしいなぁ、とボンヤリ思っている程度のものです

それからアチコチに別途要望を出すのもなんなので、ここに纏めて出しすね。
要望１　艦娘一覧画面について
１．１：艦娘バナー画像のみ（名前テキストなしorホバー表示）のオプションがあると、艦娘バナーだけで誰か判断ができる、違いのわかる提督になれるような気がします
１．２：バナーの下に艦娘名を表示させるオプションでカラム幅が節約できると、デスクトップのレイアウトに自由度がまします
要望２．
１．２同様レイアウト自由度を向上させる為の要望です。フォントサイズの設定は3種から選択だけでなく、数値入力ができる機能にしてほしい（もしくは3種それぞれに数値入力機能を追加する）
＃私の艦娘専用デスクトップのスクショを添付します。これだったらレイアウトの自由度あったほうがいいかも、とシンパシーを感じていただければ幸いです
![デスクトップキャプチャ](https://user-images.githubusercontent.com/84298721/118982058-0096c780-b9b6-11eb-8a4a-88bbe2f3f8f1.jpg)
＃デスクトップ左側が「四式電子観測儀」とスクショやツイからDLした画像を閲覧できるビューワ"Xnview"、右側にlogbook-kaiとブラウザ。これらを隙間なく設置するために「マグネットウィンドウ」というツールも常駐しています。ちなみに８周年をお祝いしてくれる大天使山風ちゃんがこのデスクトップ最大のポイントです

**Comment by Sdk0815** [comment]
@HrhtAoKanColleInKanoya ご報告ありがとうございます。確かにカラムの順番は保持されていないようですね。修正を検討します。

それ以外のご要望に関しては検討して簡単に対応できるようでしたら一緒に対応しますし、時間がかかりそうでしたらこちらでissueを分割させてもらいますね。よろしくお願いします。

**Comment by Sdk0815** [comment]
カラムの並び順の保持については `v21.7.1` で対応したしました。ご確認ください。

**Comment by HrhtAtKanColleInKanoya** [comment]
確認しました。対応ありがとうございます
