### ISSUE TITLE
大破艦が出た戦闘の終了時（戦果報告画面あたり）にも通知する設定がほしい

### ISSUE THREAD

**Issue by azhe6526** [Sdk0815/logbook-kai#47]
### 機能拡張で解決したい課題
大破艦の出た戦闘の次の戦闘が陣形選択なしで自動的に行なわれる場合でも、確実に大破進軍を回避したいです（進撃してから通知が来てあわててリロードすることを避けたい）。また、左記以外のケースでも戦闘終了時と進撃時の2回通知することで大破進撃に対する注意を確実にプレイヤーに促したいです。

### 実装してほしい機能について
大破艦の出た戦闘の終了時（戦果報告画面あたり、進撃/撤退を選ぶ前）にも通知する設定がほしいです。

### その他
特になし。

**Comment by Sdk0815** [comment]
@azhe6526 ご要望ありがとうございます。技術的には実装可能なのですが、以下の懸念点があります。

- 戦闘終了時には艦娘のHP情報が送られてこないので、万が一 logbook-kai の実装に漏れがあったり、新しいAPIが実装されたりした場合警告を行わない危険性がある（進撃選択後にはHP情報が送られてくるので警告はほぼ確実に正しいです）
- logbook-kai で警告できる状態＝艦隊タブが確実に赤くなっているので、せっかく作ってもあまり使う人はいない可能性がある

せっかく作ってもほとんど使われないとなると残念なので、Twitterでアンケート取ってみますね。それでそこそこ要望があるようでしたら検討してみようと思います。

**Comment by Sdk0815** [comment]
申し訳ありませんが開発を停止させていただくことにしましたので未実装ですがクローズさせていただきます。ありがとうございました。
