### ISSUE TITLE
2021春イベE5 Bマス空襲戦で現在の戦闘が反映されない

### ISSUE THREAD

**Issue by dexter-kankore** [Sdk0815/logbook-kai#48]
### 問題概要
イベントマップ第5海域でBマスの空襲戦で現在の戦闘が反映されない

### 再現方法
1.第三艦隊で7隻編成で出撃
2.Bマスの空襲が反映されない
3.Cマスの対潜が始まると反映される

### 動作環境
 - OS:Win10 19041.985
 - Java: 1.8.0_291
 - Version:21.5.2

**Comment by Sdk0815** [comment]
@dexter-kankore ご報告ありがとうございます。こちらで確認出来次第対応を検討します。

**Comment by dexter-kankore** [comment]
@Sdk0815 
返信ありがとうございます。艦これをリロードした影響なのか、事象が出なくなりました。再発したらまた記載します。

**Comment by tashF75** [comment]
同様の症状がイベントマップ第4海域ゲージ１でも発生していました．

1.第三艦隊で7隻編成で出撃（進軍ルート BDEGIJL）
2.Dマス，Gマスの空襲が反映されない（あとで戦闘ログの当該行をダブルクリックしても何も出ない）
3.Eマス，Iマスの戦闘が始まると反映される
（3回に2回ほど，Lマスのボス戦も反映されませんでした．）
PC再起動や艦これのリロードを試しましたが，同様の事象は起きています．

OS:Win10 19042.985
Java: 1.8.0_232
Version:21.5.2
ご参考になれば幸いです．

**Comment by dexter-kankore** [comment]
再発したので報告します。

一部分だけ反映されてるっぽいです。部分キャプチャしてみたので掲載します。
Bマスの戦闘が終了したときに画像のように中途半端に反映されている感じでした。

■Cマス戦闘後 母港に帰還のキャプチャ
![image](https://user-images.githubusercontent.com/26273425/121312351-3fc69180-c940-11eb-8c9a-997696d1409f.png)

■帰還後にBマス戦闘後からCマス戦闘開始前のキャプチャ
![image](https://user-images.githubusercontent.com/26273425/121311015-f32e8680-c93e-11eb-8cc2-447dc013ee79.png)

進軍ルートを記載してませんでした記載します。
【BCWXZ1Z】(B:空襲 C:対潜 X:通常 Z1:夜戦 Z:ボス)

**Comment by Sdk0815** [comment]
@dexter-kankore @tashF75 情報ありがとうございます。私の方でも（原因と考えられる）7隻編成での該当マスへの出撃が可能になったので試していますが、今のところ再現できていません。私が行っているのは以下ですが、何か違う点などありそうでしたらお知らせください。

- 「現在の戦闘」を開いておく（この時点では前回の最後の戦闘の情報が表示されている）
- 第三艦隊に7隻編成でE5へ出撃する
- Bマスへ到達し陣形を選んで戦闘が開始して情報が更新されるか確認

私のところではこの段階でちゃんと内容が更新されています。

@dexter-kankore すみません、上に貼っていただいたスクリーンショットですが、「帰還後にBマス戦闘後からCマス戦闘開始前のキャプチャ」を拝見してもちゃんと反映されているように見えるのですがどのあたりが反映されていないのでしょうか？ご指摘いただけるとありがたいです。

**Comment by Sdk0815** [comment]
あ、もしかすると再現したかもしれません。戦闘ログが表示できないとなかなか検証は難しいかもしれませんが、その戦闘で **7隻目の艦が対空CIを発動** していませんでしょうか？少なくとも私の環境ではその状況だと戦闘ログが表示されないことが確認できたので、原因の一つではあると考えられます。他にも7隻編成固有の問題がある可能性はあります。

**Comment by dexter-kankore** [comment]
@Sdk0815 7隻目の対空カットインを試してみました。

表示がおかしくなりました。茶色の囲い部分が反映されてないようです。
![image](https://user-images.githubusercontent.com/26273425/121780376-efb72b80-cbda-11eb-9e49-6b461958e50b.png)

オプションは「戦闘結果時に結果を反映」にしてるので経験値部分は？表示になるかとおもうのですが（挙動あってますよね）
![image](https://user-images.githubusercontent.com/26273425/121780479-75d37200-cbdb-11eb-82bb-929e1a0bdb6f.png)

**Comment by Sdk0815** [comment]
@dexter-kankore 確認ありがとうございます。7隻目の艦が対空CIを発動した場合そのような挙動になるようで、恐らく修正可能です。ただし他にもまだ7番艦の対応が漏れている可能性は否定できないので、もし7番艦が対空CIをしていないのに同様な現象が確認された場合はお知らせください。この問題は空襲戦マスに限らないので、恐らく @tashF75 さんのご報告にあるボス戦でも起きていた現象もこれではないかと思っています。

イベント期間はもう残り少ないので、なるべく早めに修正版を出したいと思っています。よろしくお願いします。

**Comment by Sdk0815** [comment]
`v21.6.1` で対応しました。こちらのバージョンでもまだ起きるようでしたら別途お知らせください。よろしくお願いいたします。

（ちなみにデータが壊れているわけではないので、以前のバージョンでひらけなかった戦闘のログもこのバージョンで開けるようになっていると思います。ご参考まで。）
