### ISSUE TITLE
戦闘ログの表が表示されない

### ISSUE THREAD

**Issue by ghost** [Sdk0815/logbook-kai#5]
### 問題概要
航海日誌 20.9.2
 コマンドタブの中の戦闘ログを開くと「表には中身がありません」とでます。

### 再現方法
1. コマンドタブ を開く
2. 戦闘ログ をクリックする
3. 表には中身がありません というエラーが出る

### 本来予想される動作
表の中身が表示される

### スクリーンショット
![スクリーンショット 2020-09-18 143808](https://user-images.githubusercontent.com/41305414/93560226-a07dfa80-f9bc-11ea-9dcf-33fe11ea96ae.png)

### 動作環境
 - OS:windows10 home 64bit
 - Java: java8 221 (ビルド1.8.0_221-b11)
 - Version:20.9.2

### その他
表示または書き込みするユニコードが間違えてると思います。

追記：書き込んでから気づいてしまったのですが「9/17メンテ対応」のissuesに書いてありました２重報告ごめんなさい

**Comment by Sdk0815** [comment]
@yokoo2211 ご報告ありがとうございます。そうなんですよね、貼っていただいたキャプチャに7-3の記録があるのでまさにその通りの問題だと思いますが、7-3に出撃してDマスを通過してしまうと”5,500t級”という文字列にカンマが含まれているためCSVが壊れてしまっています。既にCSVファイル内に記録されてしまったものは修正は困難なので、それを戦闘ログ等で読み込んだ時に補正する変更を入れる予定です。

**Comment by Sdk0815** [comment]
@yokoo2211 `v20.9.3`にて対応いたしましたのでクローズします。ご報告ありがとうございました！
