### ISSUE TITLE
雷撃戦のクリティカル判定が拾えていない

### ISSUE THREAD

**Issue by hknmtt1413** [Sdk0815/logbook-kai#50]
### 問題概要
コマンド→戦闘ログ→任意の戦闘ログ詳細画面にて、
「砲雷撃戦フェイズ」内の詳細の雷撃戦でのダメージ表示に関して、
クリティカルが発生している攻撃に「(クリティカル)」の表示がされていません。

「七四式電子観測儀」のBattleLogにて、同戦闘の内容を見ると「Critical!」の表示がされており、
他ツールでダメージ計算をした際にも、クリティカル時のダメージ範囲である事を確認しています。

### 再現方法
1.任意の海域で雷撃戦を行う
2.戦闘ログを確認する

### 本来予想される動作
1回目◯ダメージの後に「(クリティカル)」が表示される（画像は通常砲撃戦の物）
![航海日誌クリティカル表示](https://user-images.githubusercontent.com/85953281/122091202-871eb780-ce43-11eb-84d5-dfebf6da3458.jpg)

### スクリーンショット
航海日誌の戦闘ログ画面
![航海日誌戦闘ログ](https://user-images.githubusercontent.com/85953281/122088607-db746800-ce40-11eb-8c3e-86d4b0a76656.jpg)

七四式の戦闘ログ画面
![七四式戦闘ログ](https://user-images.githubusercontent.com/85953281/122088763-08287f80-ce41-11eb-98b7-b72c5a0bae7d.jpg)
航海日誌側では「長波改二」のダメージの箇所にクリティカルの表示がありませんが、
七四式のログではクリティカルの表示がされております。
（長波より前のログから同戦闘である事が分かるかと思います）

画像はイベント海域の物で、
「通常艦隊VS連合艦隊」ですが、
3-3ボスの「通常艦隊VS通常艦隊」の戦闘でも同様に発生しているので、
特別な条件は無いかと思われます。

### 動作環境
 - OS:Window10 Home
 - Java: build 1.8.0_261-b12
 - Version:21.6.1

### その他
Githubをダウンロード以外で使うのは初めてで、
プログラムに関する知識も乏しいので、
何か他に必要な情報があればご教示頂けると幸いです。

**Comment by Sdk0815** [comment]
@hknmtt1413 問題報告ありがとうございます。調査して対応を検討します。

**Comment by Sdk0815** [comment]
`v21.7.1` で修正しました。ご確認ください。（データが壊れているわけではないので過去の戦闘のデータでも正しく表示されていると思います。）

**Comment by hknmtt1413** [comment]
過去の戦闘データでクリティカル判定が正しく拾えている事を確認しました。
対応ありがとうございました。
ここで言う事ではないと思いますが、開発お疲れさまでした。とても見やすく、使いやすかったです。ありがとうございました！
