### ISSUE TITLE
戦闘ログの装備改修値が実際の戦闘時の情報と違う

### ISSUE THREAD

**Issue by SIRIUS386** [Sdk0815/logbook-kai#51]
### 問題概要
戦闘ログ参照時、表示される装備情報が実際の戦闘でログが記録された時の情報でない。

### 再現方法
１．後で確認がしやすいようにわかりやすい装備状態で出撃を行う
２．[コマンド] → [戦闘ログ] で１．の出撃で記録したログの表示内容を確認（画像１）
３．出撃時に装備していた装備を改修を行い状態を変化させる
４．改めて戦闘ログを表示する
　　→ 装備の改修値が現在の状態で表示される。（画像２）

### 本来予想される動作
実際に戦闘が行われたときの状態が表示されるべき。

### スクリーンショット
画像１
![image](https://user-images.githubusercontent.com/86059689/122409043-cbce5e00-cfbd-11eb-8b15-771027b67c08.png)

画像２
![image](https://user-images.githubusercontent.com/86059689/122409135-dd176a80-cfbd-11eb-85ae-08952b5bff4f.png)

画像３ 実際の戦闘時には12.7cm連装砲を２つ装備していたが、該当装備を破棄したあと戦闘ログを表示した場合
![image](https://user-images.githubusercontent.com/86059689/122409423-17810780-cfbe-11eb-997b-fbc4ab258c9e.png)

### 動作環境
・Windows10Pro 21H1
  Surface Pro（5th Gen） モデル 1796 i7(2コア4スレッド)
・java.version 1.8.0_291
・航海日誌 21.6.1
※上記いずれもログ記録時期によっては、より以前のVersionの場合もあり

### その他
・実際のログファイル(.json)には、戦闘時の改修値が記録されているようなので改修値や熟練度は表示処理の修正で対応が可能そう。
・ItemID参照で装備の情報を得ているようなので、破棄や上位更新が行われた場合や恐らく艦娘自体がいなくなっている場合も実際の戦闘時の情報が表示出来なくなる？（画像３）
　この点は現在の記録情報からは情報の復元は不可能そう？

・これは別件になってしまうのですが
　Kan-logkai\logs\配下のログ記録が2020年9月あたりから現在まで
  37MBなど妙に大きいのが記録されている場合があります
　中身を見ると非常に短時間に
　＞2020-09-18 19:08:25,550 WARN  l.i.MissionLogs [JavaFX Application Thread] 遠征報告書の読み込み中に例外
　＞java.lang.ArrayIndexOutOfBoundsException: null
　このようなログが大量に記録されています
　これは何か対応や確認すべきポイントやより詳細に調べるために集めるべき情報があるでしょうか？

**Comment by Sdk0815** [comment]
@SIRIUS386 ご報告ありがとうございます。

> 実際のログファイル(.json)には、戦闘時の改修値が記録されているようなので改修値や熟練度は表示処理の修正で対応が可能そう

熟練度はまだ分かりますが、改修値も記録されているんですね。確認してないですが、もしそうなら確かに対応可能であると思います。検討します。

> ItemID参照で装備の情報を得ているようなので、破棄や上位更新が行われた場合や恐らく艦娘自体がいなくなっている場合も実際の戦闘時の情報が表示出来なくなる？

こちらに関しても確認しますが、もし item id （実際の装備1つ1つに unique に割り当てられる値）が記録されているのであれば、現状は対応は難しいです。少なくとも過去のものは無理です。もし記録されているのが slotitem id （装備の種類ごとに割り当てられる値）であれば対応することは可能かも知れません。ただ少なくとも艦娘の方は id（艦娘ごとのID）が記録されていて ship id（艦ごとの ID）の方ではなかったような記憶があるので、装備の方も同様の実装であれば難しいかも知れません。

> ＞2020-09-18 19:08:25,550 WARN l.i.MissionLogs [JavaFX Application Thread] 遠征報告書の読み込み中に例外
> 　＞java.lang.ArrayIndexOutOfBoundsException: null
> 　このようなログが大量に記録されています

こちらについてはこの下にスタックトレースが出ていませんでしょうか？スタックトレースというのはこんな感じのやつです（これは別のアプリケーションのものですが）：
```
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
```
出ているのであれば、それを１セット貼っていただければ何か想像がつくかも知れません。ただ時間が経っているとその頃に何をしていたか等わからないと思うので、原因究明までは至らない可能性もあります。もし最近出ているようであればそれは別途 issue でご報告ください。

以上、よろしくお願いいたします。

**Comment by SIRIUS386** [comment]
@Sdk0815 さま 回答ありがとうございます。

自分の方でもう少しちゃんと確認してみたところ
艦娘に関しての情報はちゃんと実際の戦闘時の情報が表示されていることを確認しました。

同一の艦娘に注目して順に過去の戦闘ログを見ていくと当時のレベルで表示されていましたし、
戦闘ログ記録後、その戦闘に参加した艦娘を解体／近代化改修に使っても戦闘ログから消えることもありませんでした。
ですので.jsonファイル内のdeckmapの情報を利用して表示しているようです。(ShipIdも有りました)

装備のみ現状ではユニークidで引っ張ってきた情報をそのまま表示しているような感じです。
これも艦娘の情報表示と同じように.jsonファイル内の情報を利用すれば正しい戦闘ログが表示出来そうです。
slotitemIdの情報もありますし、levelが改修値でalvが熟練度のようです。

![image](https://user-images.githubusercontent.com/86059689/122569006-47471280-d085-11eb-99d6-f173affb4f48.png)

また、追加要望になってしまうのですが
戦闘ログ時点と現在では状況は変わっており、居なくなった艦娘、無くなった装備などもあると思います
表示時に文字色を灰色に変えるなどして、現在は居ないよ／無いよ っていう情報も分かるといいかなと思いました
これは戦闘ログ表示時にユニークidでの情報が取得出来る／出来ないで現在も居るか居ないか、装備が有るか無いかが判別出来るのではないかと思います。

以上の件
気力体力時間が有るときに対応いただければと思います。
どうぞよろしくお願いします。

**Comment by SIRIUS386** [comment]
>＞2020-09-18 19:08:25,550 WARN l.i.MissionLogs [JavaFX Application Thread] 遠征報告書の読み込み中に例外
>　＞java.lang.ArrayIndexOutOfBoundsException: null
>　このようなログが大量に記録されています

この件について自己解決できましたので報告いたします。
(新たなissueにする必要は無いと思われるためここに書き込ませていただきます）

原因は 遠征報告書.csv の内容でした
ファイル内に旧版航海日誌(Kancolle-log)からの古いフォーマットが混じっていたためで、
この状態で[コマンド] → [遠征ログ] で 遠征ログ画面を表示すると、
そのたびに大量に[遠征報告書の読み込み中に例外]が記録されていました。

![遠征報告書csv中身](https://user-images.githubusercontent.com/86059689/122629125-b6f4e600-d0f5-11eb-9256-fc4217d76869.jpg)

17566行より上(見出し行除く)の内容を取り除いてみたところ、遠征ログ画面を表示してもエラーログの記録は発生しなくなりました。

**Comment by Sdk0815** [comment]
`v21.7.1` で修正しました。ご確認ください。存在しない装備をグレーアウトする等の拡張は行なっていませんがご容赦いただけると幸いです。

**Comment by SIRIUS386** [comment]
@Sdk0815 さま
最初に問題に気がついたときの戦闘ログとここでの報告で使用した戦闘ログの2つで
実際の戦闘時の情報が表示されることを確認しました。
対応ありがとうございました。

> 存在しない装備をグレーアウトする等の拡張は行なっていませんがご容赦いただけると幸いです。

いえこちらこそ突発的な思いつきで余計な作業が増えるようなことを言ってすみませんでした。

戦闘ログは仮に将来艦これのサービスが終了したとしても、
当時のプレイを思い出す事のできる大切な情報です、それが正しく表示出来るだけで充分です。
本当に感謝です。
