### ISSUE TITLE
大破警告が誤って表示される

### ISSUE THREAD

**Issue by musasab1** [Sdk0815/logbook-kai#52]
### 問題概要
出撃中の艦隊ではなく、母港にいる大破艦の警告が誤って表示される

### 再現方法
連合艦隊を組んだ状態で第二艦隊に（入渠中でも入渠していなくても）大破艦を置いた状態で、
7隻の遊撃艦隊でE4に出撃したところ、進撃する度に第二艦隊の大破艦警告が表示される

### 本来予想される動作
表示されなくて良いと思います

### スクリーンショット

![無題](https://user-images.githubusercontent.com/19219151/122675313-d1bd7c80-d213-11eb-9340-90594bc4d8e5.png)

### 動作環境
 - OS: windows10 64bit （バージョン10.0.19043 ビルド 19043）
 - Java:  ビルド1.8.0_291-b10
 - Version: v21.6.1

### その他
バグ報告初めてなので不備点あればご指摘お願いします

**Comment by Sdk0815** [comment]
@musasab1 ご報告ありがとうございます。確認して対応を検討します。

**Comment by Sdk0815** [comment]
`v21.7.1` で修正しました。次回以降のイベントでご確認いただければと思います。

**Comment by musasab1** [comment]
早速の対応と日々の更新ありがとうございます。
