### ISSUE TITLE
現在の戦闘・演習 被害状況の画像表示

### ISSUE THREAD

**Issue by manu3da4** [Sdk0815/logbook-kai#60]
21.8.1に更新後、現在の戦闘と現在の演習で被害状況の画像表示の文字部分がおかしい。被害と画像がずれている?
小破 → 退避
撃沈 → 損壊
など

![戦闘ログのスナップショット20210822b](https://user-images.githubusercontent.com/42598011/130341808-eeeac314-9eac-4fb5-8d57-5db1eec23ae5.png)
![戦闘ログのスナップショット20210822](https://user-images.githubusercontent.com/42598011/130341809-c7a91c44-d28d-4838-b9bb-c8f6b5273e95.png)

動作環境
 - OS: Windows
 - Java: Java8

**Comment by Sdk0815** [comment]
他の方からは特に問題なく表示されているとの報告もありますので、キャッシュをクリアするとか再起動してみるなどで解決するかもしれません。お試しください。

もしそれで直らなかったとしても本プロジェクトは既に開発終了しておりますので対応は控えさせていただきます。ご了承ください。
