### ISSUE TITLE
周遊装備数が合わない

### ISSUE THREAD

**Issue by HhitsunN** [Sdk0815/logbook-kai#61]
### 問題概要
所有装備の数が異なっている

### 再現方法
航海日誌の所有装備の数とゲーム内のものを確認する

### 本来予想される動作
その他をご確認ください

### その他
装備枠としてカウントされなくなったアイテムができました。
その分差異が発生しています。
運営のツイート内容は以下のとおりです。
更新不能とありましたが、対応できますでしょうか。
よろしくお願いします
－－－
艦隊の【装備運用枠】は、前述【母港拡張】によって拡張可能ですが、下記装備の更新実装によって、
【装備運用枠】をより柔軟に活用可能です。
●応急修理要員
●応急修理女神
●戦闘糧食
●戦闘糧食(特別なおにぎり)
●秋刀魚の缶詰
●洋上補給
を【装備運用枠】から分離して、それぞれの上限枠の中で運用可能となります。
※本更新実装は、無課金で自動的に更新されます。

**Comment by Sdk0815** [comment]
@HhitsunN 既にお知らせ済みの通り、更新は終了しておりますので対応は行いません。ご了承ください。正確には把握しておりませんが、こちらのソースコードを元に個別に対応してくださっている方々がおられるようですので、そちらを探していただけるのも良いかもしれません。よろしくお願いします。
